-- 删除菜单并撤销权限

DELETE FROM SYSTEM_ROLE_MENU WHERE MENU_ID IN (SELECT ID FROM SYSTEM_MENU WHERE `PATH` = '/system/system-config');
DELETE FROM SYSTEM_MENU WHERE `PATH` = '/system/config';

-- 删除权限并撤销角色分配

DELETE FROM `SYSTEM_ROLE_PERMISSION` WHERE PERMISSION_ID IN (SELECT ID FROM `SYSTEM_PERMISSION` WHERE `CODE` = 'system:config:create');
DELETE FROM `SYSTEM_PERMISSION` WHERE `CODE` = 'system:config:create';

DELETE FROM `SYSTEM_ROLE_PERMISSION` WHERE PERMISSION_ID IN (SELECT ID FROM `SYSTEM_PERMISSION` WHERE `CODE` = 'system:config:delete');
DELETE FROM `SYSTEM_PERMISSION` WHERE `CODE` = 'system:config:delete';

DELETE FROM `SYSTEM_ROLE_PERMISSION` WHERE PERMISSION_ID IN (SELECT ID FROM `SYSTEM_PERMISSION` WHERE `CODE` = 'system:config:update');
DELETE FROM `SYSTEM_PERMISSION` WHERE `CODE` = 'system:config:update';

DELETE FROM `SYSTEM_ROLE_PERMISSION` WHERE PERMISSION_ID IN (SELECT ID FROM `SYSTEM_PERMISSION` WHERE `CODE` = 'system:config:query');
DELETE FROM `SYSTEM_PERMISSION` WHERE `CODE` = 'system:config:query';
